# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r
language: R
cache: packages
warnings_are_errors: false
cran: http://cran.rstudio.com
r_github_packages:
  - r-lib/pkgdown
  - r-lib/covr
r:
  - oldrel
  - release
  - devel
after_success:
  - Rscript -e 'covr::codecov()'
